// <ref *2> IncomingMessage {
//     _readableState: ReadableState {
//       objectMode: false,
//       highWaterMark: 16384,
//       buffer: BufferList { head: null, tail: null, length: 0 },
//       length: 0,
//       pipes: [],
//       flowing: true,
//       ended: true,
//       endEmitted: true,
//       reading: false,
//       constructed: true,
//       sync: false,
//       needReadable: false,
//       emittedReadable: false,
//       readableListening: false,
//       resumeScheduled: false,
//       errorEmitted: false,
//       emitClose: true,
//       autoDestroy: true,
//       destroyed: true,
//       errored: null,
//       closed: true,
//       closeEmitted: true,
//       defaultEncoding: 'utf8',
//       awaitDrainWriters: null,
//       multiAwaitDrain: false,
//       readingMore: false,
//       dataEmitted: true,
//       decoder: null,
//       encoding: null,
//       [Symbol(kPaused)]: false
//     },
//     _events: [Object: null prototype] {},
//     _eventsCount: 0,
//     _maxListeners: undefined,
//     socket: <ref *1> Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _closeAfterHandlingError: false,
//       _readableState: ReadableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//         pipes: [],
//         flowing: true,
//         ended: false,
//         endEmitted: false,
//         reading: true,
//         constructed: true,
//         sync: false,
//         needReadable: true,
//         emittedReadable: false,
//         readableListening: false,
//         resumeScheduled: false,
//         errorEmitted: false,
//         emitClose: false,
//         autoDestroy: true,
//         destroyed: false,
//         errored: null,
//         closed: false,
//         closeEmitted: false,
//         defaultEncoding: 'utf8',
//         awaitDrainWriters: null,
//         multiAwaitDrain: false,
//         readingMore: false,
//         dataEmitted: false,
//         decoder: null,
//         encoding: null,
//         [Symbol(kPaused)]: false
//       },
//       _events: [Object: null prototype] {
//         end: [Array],
//         timeout: [Function: socketOnTimeout],
//         data: [Function: bound socketOnData],
//         error: [Function: socketOnError],
//         close: [Array],
//         drain: [Function: bound socketOnDrain],
//         resume: [Function: onSocketResume],
//         pause: [Function: onSocketPause]
//       },
//       _eventsCount: 8,
//       _maxListeners: undefined,
//       _writableState: WritableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         finalCalled: false,
//         needDrain: false,
//         ending: false,
//         ended: false,
//         finished: false,
//         destroyed: false,
//         decodeStrings: false,
//         defaultEncoding: 'utf8',
//         length: 0,
//         writing: false,
//         corked: 0,
//         sync: false,
//         bufferProcessing: false,
//         onwrite: [Function: bound onwrite],
//         writecb: null,
//         writelen: 0,
//         afterWriteTickInfo: null,
//         buffered: [],
//         bufferedIndex: 0,
//         allBuffers: true,
//         allNoop: true,
//         pendingcb: 0,
//         constructed: true,
//         prefinished: false,
//         errorEmitted: false,
//         emitClose: false,
//         autoDestroy: true,
//         errored: null,
//         closed: false,
//         closeEmitted: false,
//         [Symbol(kOnFinished)]: []
//       },
//       allowHalfOpen: true,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: Server {
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         requestTimeout: 300000,
//         headersTimeout: 60000,
//         keepAliveTimeout: 5000,
//         connectionsCheckingInterval: 30000,
//         joinDuplicateHeaders: undefined,
//         rejectNonStandardBodyWrites: false,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 1,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         noDelay: true,
//         keepAlive: false,
//         keepAliveInitialDelay: 0,
//         highWaterMark: 16384,
//         httpAllowHalfOpen: false,
//         timeout: 0,
//         maxHeadersCount: null,
//         maxRequestsPerSocket: 0,
//         _connectionKey: '6::::3333',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(async_id_symbol)]: 12349,
//         [Symbol(http.server.connections)]: ConnectionsList {},
//         [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//           _idleTimeout: 30000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 30541,
//           _onTimeout: [Function: bound checkConnections],
//           _timerArgs: undefined,
//           _repeat: 30000,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 8,
//           [Symbol(triggerId)]: 0
//         },
//         [Symbol(kUniqueHeaders)]: null
//       },
//       _server: Server {
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         requestTimeout: 300000,
//         headersTimeout: 60000,
//         keepAliveTimeout: 5000,
//         connectionsCheckingInterval: 30000,
//         joinDuplicateHeaders: undefined,
//         rejectNonStandardBodyWrites: false,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 1,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         noDelay: true,
//         keepAlive: false,
//         keepAliveInitialDelay: 0,
//         highWaterMark: 16384,
//         httpAllowHalfOpen: false,
//         timeout: 0,
//         maxHeadersCount: null,
//         maxRequestsPerSocket: 0,
//         _connectionKey: '6::::3333',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(async_id_symbol)]: 12349,
//         [Symbol(http.server.connections)]: ConnectionsList {},
//         [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//           _idleTimeout: 30000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 30541,
//           _onTimeout: [Function: bound checkConnections],
//           _timerArgs: undefined,
//           _repeat: 30000,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 8,
//           [Symbol(triggerId)]: 0
//         },
//         [Symbol(kUniqueHeaders)]: null
//       },
//       parser: HTTPParser {
//         '0': null,
//         '1': [Function: parserOnHeaders],
//         '2': [Function: parserOnHeadersComplete],
//         '3': [Function: parserOnBody],
//         '4': [Function: parserOnMessageComplete],
//         '5': [Function: bound onParserExecute],
//         '6': [Function: bound onParserTimeout],
//         _headers: [],
//         _url: '',
//         socket: [Circular *1],
//         incoming: [Circular *2],
//         outgoing: null,
//         maxHeaderPairs: 2000,
//         _consumed: true,
//         onIncoming: [Function: bound parserOnIncoming],
//         [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
//       },
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       setEncoding: [Function: socketSetEncoding],
//       _paused: false,
//       _httpMessage: ServerResponse {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: false,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: true,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: true,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: null,
//         _hasBody: true,
//         _trailer: '',
//         finished: false,
//         _headerSent: false,
//         _closed: false,
//         socket: [Circular *1],
//         _header: null,
//         _keepAliveTimeout: 5000,
//         _onPendingData: [Function: bound updateOutgoingData],
//         req: [Circular *2],
//         _sent100: false,
//         _expect_continue: false,
//         _maxRequestsPerSocket: 0,
//         locals: [Object: null prototype] {},
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype],
//         [Symbol(errored)]: null,
//         [Symbol(kHighWaterMark)]: 16384,
//         [Symbol(kRejectNonStandardBodyWrites)]: false,
//         [Symbol(kUniqueHeaders)]: null
//       },
//       timeout: 0,
//       [Symbol(async_id_symbol)]: 32243,
//       [Symbol(kHandle)]: TCP {
//         reading: true,
//         onconnection: null,
//         _consumed: true,
//         [Symbol(owner_symbol)]: [Circular *1]
//       },
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: Timeout {
//         _idleTimeout: -1,
//         _idlePrev: null,
//         _idleNext: null,
//         _idleStart: 24729,
//         _onTimeout: null,
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: true,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 32264,
//         [Symbol(triggerId)]: 32262
//       },
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(kCapture)]: false,
//       [Symbol(kSetNoDelay)]: true,
//       [Symbol(kSetKeepAlive)]: false,
//       [Symbol(kSetKeepAliveInitialDelay)]: 0,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     httpVersionMajor: 1,
//     httpVersionMinor: 1,
//     httpVersion: '1.1',
//     complete: true,
//     rawHeaders: [
//       'content-type',
//       'application/json',
//       'authorization',
//       'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IklJLWdsQVpldzl2aVNfLWFyT3gzSCJ9.eyJpc3MiOiJodHRwczovL2Rldi1sZmZ2b2Z5cnk2a2o1NG80LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMTkzMDQwMjg2NzA5ODg5ODA5OCIsImF1ZCI6WyJpZ25pdGUtbGFiLWF1dGgtcmtiIiwiaHR0cHM6Ly9kZXYtbGZmdm9meXJ5NmtqNTRvNC51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzAyNDgzNTI0LCJleHAiOjE3MDI1Njk5MjQsImF6cCI6InVoVFdrd2FydTRDSTVzTnRoRFVubUthTVdCNzVBZnpUIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XxNM0vrx3f0X-pt10AH46ejCGsA079h_Tg8g2l8P8upcNRIEfocgYq9cjDnqp4_7fiO6PblXU8KEB6SBizfNjOjQMCucOE74YqICse6cOrGkWJDVY2-HperiW08rMDHSGEjp4NX6TIKrvLadbi5-p3OSCkfyTBkwtnui5SKfqh4LKgJgYPRuevf-MQN0GqcYujddsZ-BrL4tKs_0rti9S8rgsjHhr0aWIO_-mAs0zSy5TopYZuTxQ863kv_uAZ51XyKO9m0eS4CVppq9XbX1sa2gbbu70WF95axNbR8rb7f2zkawPb3WgDpEi5LpcxoRKH8peCEhM86QGMtjyyzOSQ',
//       'Accept',
//       '*/*',
//       'Content-Length',
//       '241',
//       'User-Agent',
//       'minipass-fetch/3.0.4 (+https://github.com/isaacs/minipass-fetch)',
//       'Accept-Encoding',
//       'gzip,deflate',
//       'Host',
//       'localhost:3333',
//       'Connection',
//       'keep-alive'
//     ],
//     rawTrailers: [],
//     joinDuplicateHeaders: undefined,
//     aborted: false,
//     upgrade: false,
//     url: '/',
//     method: 'POST',
//     statusCode: null,
//     statusMessage: null,
//     client: <ref *1> Socket {
//       connecting: false,
//       _hadError: false,
//       _parent: null,
//       _host: null,
//       _closeAfterHandlingError: false,
//       _readableState: ReadableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//         pipes: [],
//         flowing: true,
//         ended: false,
//         endEmitted: false,
//         reading: true,
//         constructed: true,
//         sync: false,
//         needReadable: true,
//         emittedReadable: false,
//         readableListening: false,
//         resumeScheduled: false,
//         errorEmitted: false,
//         emitClose: false,
//         autoDestroy: true,
//         destroyed: false,
//         errored: null,
//         closed: false,
//         closeEmitted: false,
//         defaultEncoding: 'utf8',
//         awaitDrainWriters: null,
//         multiAwaitDrain: false,
//         readingMore: false,
//         dataEmitted: false,
//         decoder: null,
//         encoding: null,
//         [Symbol(kPaused)]: false
//       },
//       _events: [Object: null prototype] {
//         end: [Array],
//         timeout: [Function: socketOnTimeout],
//         data: [Function: bound socketOnData],
//         error: [Function: socketOnError],
//         close: [Array],
//         drain: [Function: bound socketOnDrain],
//         resume: [Function: onSocketResume],
//         pause: [Function: onSocketPause]
//       },
//       _eventsCount: 8,
//       _maxListeners: undefined,
//       _writableState: WritableState {
//         objectMode: false,
//         highWaterMark: 16384,
//         finalCalled: false,
//         needDrain: false,
//         ending: false,
//         ended: false,
//         finished: false,
//         destroyed: false,
//         decodeStrings: false,
//         defaultEncoding: 'utf8',
//         length: 0,
//         writing: false,
//         corked: 0,
//         sync: false,
//         bufferProcessing: false,
//         onwrite: [Function: bound onwrite],
//         writecb: null,
//         writelen: 0,
//         afterWriteTickInfo: null,
//         buffered: [],
//         bufferedIndex: 0,
//         allBuffers: true,
//         allNoop: true,
//         pendingcb: 0,
//         constructed: true,
//         prefinished: false,
//         errorEmitted: false,
//         emitClose: false,
//         autoDestroy: true,
//         errored: null,
//         closed: false,
//         closeEmitted: false,
//         [Symbol(kOnFinished)]: []
//       },
//       allowHalfOpen: true,
//       _sockname: null,
//       _pendingData: null,
//       _pendingEncoding: '',
//       server: Server {
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         requestTimeout: 300000,
//         headersTimeout: 60000,
//         keepAliveTimeout: 5000,
//         connectionsCheckingInterval: 30000,
//         joinDuplicateHeaders: undefined,
//         rejectNonStandardBodyWrites: false,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 1,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         noDelay: true,
//         keepAlive: false,
//         keepAliveInitialDelay: 0,
//         highWaterMark: 16384,
//         httpAllowHalfOpen: false,
//         timeout: 0,
//         maxHeadersCount: null,
//         maxRequestsPerSocket: 0,
//         _connectionKey: '6::::3333',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(async_id_symbol)]: 12349,
//         [Symbol(http.server.connections)]: ConnectionsList {},
//         [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//           _idleTimeout: 30000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 30541,
//           _onTimeout: [Function: bound checkConnections],
//           _timerArgs: undefined,
//           _repeat: 30000,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 8,
//           [Symbol(triggerId)]: 0
//         },
//         [Symbol(kUniqueHeaders)]: null
//       },
//       _server: Server {
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         requestTimeout: 300000,
//         headersTimeout: 60000,
//         keepAliveTimeout: 5000,
//         connectionsCheckingInterval: 30000,
//         joinDuplicateHeaders: undefined,
//         rejectNonStandardBodyWrites: false,
//         _events: [Object: null prototype],
//         _eventsCount: 2,
//         _maxListeners: undefined,
//         _connections: 1,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         noDelay: true,
//         keepAlive: false,
//         keepAliveInitialDelay: 0,
//         highWaterMark: 16384,
//         httpAllowHalfOpen: false,
//         timeout: 0,
//         maxHeadersCount: null,
//         maxRequestsPerSocket: 0,
//         _connectionKey: '6::::3333',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(async_id_symbol)]: 12349,
//         [Symbol(http.server.connections)]: ConnectionsList {},
//         [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//           _idleTimeout: 30000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 30541,
//           _onTimeout: [Function: bound checkConnections],
//           _timerArgs: undefined,
//           _repeat: 30000,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 8,
//           [Symbol(triggerId)]: 0
//         },
//         [Symbol(kUniqueHeaders)]: null
//       },
//       parser: HTTPParser {
//         '0': null,
//         '1': [Function: parserOnHeaders],
//         '2': [Function: parserOnHeadersComplete],
//         '3': [Function: parserOnBody],
//         '4': [Function: parserOnMessageComplete],
//         '5': [Function: bound onParserExecute],
//         '6': [Function: bound onParserTimeout],
//         _headers: [],
//         _url: '',
//         socket: [Circular *1],
//         incoming: [Circular *2],
//         outgoing: null,
//         maxHeaderPairs: 2000,
//         _consumed: true,
//         onIncoming: [Function: bound parserOnIncoming],
//         [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
//       },
//       on: [Function: socketListenerWrap],
//       addListener: [Function: socketListenerWrap],
//       prependListener: [Function: socketListenerWrap],
//       setEncoding: [Function: socketSetEncoding],
//       _paused: false,
//       _httpMessage: ServerResponse {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         outputData: [],
//         outputSize: 0,
//         writable: true,
//         destroyed: false,
//         _last: false,
//         chunkedEncoding: false,
//         shouldKeepAlive: true,
//         maxRequestsOnConnectionReached: false,
//         _defaultKeepAlive: true,
//         useChunkedEncodingByDefault: true,
//         sendDate: true,
//         _removedConnection: false,
//         _removedContLen: false,
//         _removedTE: false,
//         strictContentLength: false,
//         _contentLength: null,
//         _hasBody: true,
//         _trailer: '',
//         finished: false,
//         _headerSent: false,
//         _closed: false,
//         socket: [Circular *1],
//         _header: null,
//         _keepAliveTimeout: 5000,
//         _onPendingData: [Function: bound updateOutgoingData],
//         req: [Circular *2],
//         _sent100: false,
//         _expect_continue: false,
//         _maxRequestsPerSocket: 0,
//         locals: [Object: null prototype] {},
//         [Symbol(kCapture)]: false,
//         [Symbol(kBytesWritten)]: 0,
//         [Symbol(kNeedDrain)]: false,
//         [Symbol(corked)]: 0,
//         [Symbol(kOutHeaders)]: [Object: null prototype],
//         [Symbol(errored)]: null,
//         [Symbol(kHighWaterMark)]: 16384,
//         [Symbol(kRejectNonStandardBodyWrites)]: false,
//         [Symbol(kUniqueHeaders)]: null
//       },
//       timeout: 0,
//       [Symbol(async_id_symbol)]: 32243,
//       [Symbol(kHandle)]: TCP {
//         reading: true,
//         onconnection: null,
//         _consumed: true,
//         [Symbol(owner_symbol)]: [Circular *1]
//       },
//       [Symbol(lastWriteQueueSize)]: 0,
//       [Symbol(timeout)]: Timeout {
//         _idleTimeout: -1,
//         _idlePrev: null,
//         _idleNext: null,
//         _idleStart: 24729,
//         _onTimeout: null,
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: true,
//         [Symbol(refed)]: false,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 32264,
//         [Symbol(triggerId)]: 32262
//       },
//       [Symbol(kBuffer)]: null,
//       [Symbol(kBufferCb)]: null,
//       [Symbol(kBufferGen)]: null,
//       [Symbol(kCapture)]: false,
//       [Symbol(kSetNoDelay)]: true,
//       [Symbol(kSetKeepAlive)]: false,
//       [Symbol(kSetKeepAliveInitialDelay)]: 0,
//       [Symbol(kBytesRead)]: 0,
//       [Symbol(kBytesWritten)]: 0
//     },
//     _consuming: true,
//     _dumped: false,
//     next: [Function: next],
//     baseUrl: '/graphql',
//     originalUrl: '/graphql',
//     _parsedUrl: Url {
//       protocol: null,
//       slashes: null,
//       auth: null,
//       host: null,
//       port: null,
//       hostname: null,
//       hash: null,
//       search: null,
//       query: null,
//       pathname: '/graphql',
//       path: '/graphql',
//       href: '/graphql',
//       _raw: '/graphql'
//     },
//     params: {},
//     query: {},
//     res: <ref *3> ServerResponse {
//       _events: [Object: null prototype] { finish: [Array] },
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       outputData: [],
//       outputSize: 0,
//       writable: true,
//       destroyed: false,
//       _last: false,
//       chunkedEncoding: false,
//       shouldKeepAlive: true,
//       maxRequestsOnConnectionReached: false,
//       _defaultKeepAlive: true,
//       useChunkedEncodingByDefault: true,
//       sendDate: true,
//       _removedConnection: false,
//       _removedContLen: false,
//       _removedTE: false,
//       strictContentLength: false,
//       _contentLength: null,
//       _hasBody: true,
//       _trailer: '',
//       finished: false,
//       _headerSent: false,
//       _closed: false,
//       socket: <ref *1> Socket {
//         connecting: false,
//         _hadError: false,
//         _parent: null,
//         _host: null,
//         _closeAfterHandlingError: false,
//         _readableState: [ReadableState],
//         _events: [Object: null prototype],
//         _eventsCount: 8,
//         _maxListeners: undefined,
//         _writableState: [WritableState],
//         allowHalfOpen: true,
//         _sockname: null,
//         _pendingData: null,
//         _pendingEncoding: '',
//         server: [Server],
//         _server: [Server],
//         parser: [HTTPParser],
//         on: [Function: socketListenerWrap],
//         addListener: [Function: socketListenerWrap],
//         prependListener: [Function: socketListenerWrap],
//         setEncoding: [Function: socketSetEncoding],
//         _paused: false,
//         _httpMessage: [Circular *3],
//         timeout: 0,
//         [Symbol(async_id_symbol)]: 32243,
//         [Symbol(kHandle)]: [TCP],
//         [Symbol(lastWriteQueueSize)]: 0,
//         [Symbol(timeout)]: Timeout {
//           _idleTimeout: -1,
//           _idlePrev: null,
//           _idleNext: null,
//           _idleStart: 24729,
//           _onTimeout: null,
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: true,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 32264,
//           [Symbol(triggerId)]: 32262
//         },
//         [Symbol(kBuffer)]: null,
//         [Symbol(kBufferCb)]: null,
//         [Symbol(kBufferGen)]: null,
//         [Symbol(kCapture)]: false,
//         [Symbol(kSetNoDelay)]: true,
//         [Symbol(kSetKeepAlive)]: false,
//         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//         [Symbol(kBytesRead)]: 0,
//         [Symbol(kBytesWritten)]: 0
//       },
//       _header: null,
//       _keepAliveTimeout: 5000,
//       _onPendingData: [Function: bound updateOutgoingData],
//       req: [Circular *2],
//       _sent100: false,
//       _expect_continue: false,
//       _maxRequestsPerSocket: 0,
//       locals: [Object: null prototype] {},
//       [Symbol(kCapture)]: false,
//       [Symbol(kBytesWritten)]: 0,
//       [Symbol(kNeedDrain)]: false,
//       [Symbol(corked)]: 0,
//       [Symbol(kOutHeaders)]: [Object: null prototype] {
//         'x-powered-by': [Array],
//         'access-control-allow-origin': [Array]
//       },
//       [Symbol(errored)]: null,
//       [Symbol(kHighWaterMark)]: 16384,
//       [Symbol(kRejectNonStandardBodyWrites)]: false,
//       [Symbol(kUniqueHeaders)]: null
//     },
//     body: {
//       query: 'mutation CreatePurchase__purchases__0($productId:String!){createPurchase(data:{productId:$productId}){__typename id}}',
//       variables: { productId: '822ef8c9-d970-4af6-9b31-142c4eaf60f3' },
//       operationName: 'CreatePurchase__purchases__0'
//     },
//     _body: true,
//     length: undefined,
//     auth: {
//       payload: {
//         iss: 'https://dev-lffvofyry6kj54o4.us.auth0.com/',
//         sub: 'google-oauth2|101930402867098898098',
//         aud: [Array],
//         iat: 1702483524,
//         exp: 1702569924,
//         azp: 'uhTWkwaru4CI5sNthDUnmKaMWB75AfzT',
//         scope: 'openid profile email'
//       },
//       header: { alg: 'RS256', typ: 'JWT', kid: 'II-glAZew9viS_-arOx3H' },
//       token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IklJLWdsQVpldzl2aVNfLWFyT3gzSCJ9.eyJpc3MiOiJodHRwczovL2Rldi1sZmZ2b2Z5cnk2a2o1NG80LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMTkzMDQwMjg2NzA5ODg5ODA5OCIsImF1ZCI6WyJpZ25pdGUtbGFiLWF1dGgtcmtiIiwiaHR0cHM6Ly9kZXYtbGZmdm9meXJ5NmtqNTRvNC51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzAyNDgzNTI0LCJleHAiOjE3MDI1Njk5MjQsImF6cCI6InVoVFdrd2FydTRDSTVzTnRoRFVubUthTVdCNzVBZnpUIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XxNM0vrx3f0X-pt10AH46ejCGsA079h_Tg8g2l8P8upcNRIEfocgYq9cjDnqp4_7fiO6PblXU8KEB6SBizfNjOjQMCucOE74YqICse6cOrGkWJDVY2-HperiW08rMDHSGEjp4NX6TIKrvLadbi5-p3OSCkfyTBkwtnui5SKfqh4LKgJgYPRuevf-MQN0GqcYujddsZ-BrL4tKs_0rti9S8rgsjHhr0aWIO_-mAs0zSy5TopYZuTxQ863kv_uAZ51XyKO9m0eS4CVppq9XbX1sa2gbbu70WF95axNbR8rb7f2zkawPb3WgDpEi5LpcxoRKH8peCEhM86QGMtjyyzOSQ'
//     },
//     [Symbol(kCapture)]: false,
//     [Symbol(kHeaders)]: {
//       'content-type': 'application/json',
//       authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IklJLWdsQVpldzl2aVNfLWFyT3gzSCJ9.eyJpc3MiOiJodHRwczovL2Rldi1sZmZ2b2Z5cnk2a2o1NG80LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMTkzMDQwMjg2NzA5ODg5ODA5OCIsImF1ZCI6WyJpZ25pdGUtbGFiLWF1dGgtcmtiIiwiaHR0cHM6Ly9kZXYtbGZmdm9meXJ5NmtqNTRvNC51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzAyNDgzNTI0LCJleHAiOjE3MDI1Njk5MjQsImF6cCI6InVoVFdrd2FydTRDSTVzTnRoRFVubUthTVdCNzVBZnpUIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.XxNM0vrx3f0X-pt10AH46ejCGsA079h_Tg8g2l8P8upcNRIEfocgYq9cjDnqp4_7fiO6PblXU8KEB6SBizfNjOjQMCucOE74YqICse6cOrGkWJDVY2-HperiW08rMDHSGEjp4NX6TIKrvLadbi5-p3OSCkfyTBkwtnui5SKfqh4LKgJgYPRuevf-MQN0GqcYujddsZ-BrL4tKs_0rti9S8rgsjHhr0aWIO_-mAs0zSy5TopYZuTxQ863kv_uAZ51XyKO9m0eS4CVppq9XbX1sa2gbbu70WF95axNbR8rb7f2zkawPb3WgDpEi5LpcxoRKH8peCEhM86QGMtjyyzOSQ',
//       accept: '*/*',
//       'content-length': '241',
//       'user-agent': 'minipass-fetch/3.0.4 (+https://github.com/isaacs/minipass-fetch)',
//       'accept-encoding': 'gzip,deflate',
//       host: 'localhost:3333',
//       connection: 'keep-alive'
//     },
//     [Symbol(kHeadersCount)]: 16,
//     [Symbol(kTrailers)]: null,
//     [Symbol(kTrailersCount)]: 0
//   }
